{{- if .Values.sealedSecrets.cloudflaredTunnel.token }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel
spec:
  encryptedData:
    token: {{ .Values.sealedSecrets.cloudflaredTunnel.token | quote }}
  template:
    metadata:
      name: cloudflare-tunnel
    type: Opaque
{{- end }}
