apiVersion: v1
kind: Service
metadata:
  name: {{ include "cassandra-yt-mcp.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "cassandra-yt-mcp.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
